const Images = {
    search: require('./search.png'),
    beoPlay: require('./beoPlay.png'),
    headphone1: require('./headphone1.png'),
    beoLit: require('./beoLit.png') ,
    beoSound:require('./beoSound.png'),
    beoplay1:require("./beoplay1.png") ,
    headPhone:require("./headPhone.png") ,
    button:require("./Button.jpg"),
    close:require("./close.png"),
    eye:require("./eye.jpg"),
    Facebook:require("./Facebook.jpg"),
    location:require("./location.jpg"),
    lock:require("./lock.jpg"),
    login:require("./log-in.png"),
    Timer:require("./Timer.png"),
    Username:require("./Username.jpg"),
    welcome:require("./WELCOME.jpg"),
    arrow:require('./arrow.png'),
    Combined:require('./Combined.png'),
    beo:require('./beo.png'),
    base:require('./Base.png'),
    indicator:require('./Indicator.png'),
    men:require('./men.png'),
    women:require('./women.png'),
    both:require('./both.png'),
    bar:require('./Bar.png'),
    min:require('./Min.png'),
    max:require('./Max.png')

}
export default Images;